spring.application.name=Patient Service

## Port Configuration
#server.port=4000
#
## H2 Database Setup
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=123
#
## Enable H2 Console
#spring.h2.console.enabled=true
#
## Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## Allow static resources (needed for Spring Boot 4.x)
#spring.web.resources.add-mappings=true
